language: go
dist: trusty
services:
  - postgresql
addons:
  postgresql: "9.5"
before_script:
  - psql -c 'CREATE DATABASE servicemap;' -U postgres
  - psql -c 'CREATE ROLE serviceapi;' -U postgres
  - psql -c 'ALTER ROLE serviceapi WITH login;' -U postgres
  - psql -c 'ALTER ROLE serviceapi PASSWORD null;' -U postgres
script:
  - make runtests
  - zip -r service-map *
  - mkdir s3_upload
  - mv service-map.zip s3_upload/service-map.zip
install: true
