language: go
dist: trusty
deploy:
  - provider: s3
    access_key_id: $AKID
    secret_access_key: $AK
    bucket: $BUCKET
    local_dir: s3_upload
    skip_cleanup: true
    on:
      branch: master
  - provider: codedeploy
    access_key_id: $AKID
    secret_access_key: $AK
    bucket: $BUCKET
    key: service-map.zip
    application: service-map
    deployment_group: service-map
    region: us-west-2
    on:
      branch: master
services:
  - postgresql
addons:
  postgresql: "9.5"
before_script:
  - psql -c 'CREATE DATABASE servicemap;' -U postgres
  - psql -c 'CREATE ROLE serviceapi;' -U postgres
  - psql -c 'ALTER ROLE serviceapi WITH login;' -U postgres
  - psql -c 'ALTER ROLE serviceapi PASSWORD null;' -U postgres
script:
  - make runtests
  - zip -r service-map *
  - mkdir s3_upload
  - mv service-map.zip s3_upload/service-map.zip
install: true
