language: go
deploy:
  - provider: s3
    access_key_id: $DEVAKID
    secret_access_key: $DEVAK
    bucket: $DEVBUCKET
    local_dir: s3_upload
    skip_cleanup: true
    on:
      branch: master
  - provider: codedeploy
    access_key_id: $DEVAKID
    secret_access_key: $DEVAK
    bucket: $DEVBUCKET
    key: service-map.zip
    application: service-map-dev
    deployment_group: service-map-dev
    region: us-west-2
script:
  - go test -v ./servicelib
  - go test -v ./serviceapi
  - zip -r service-map *
  - mkdir s3_upload
  - mv service-map.zip s3_upload/service-map.zip
install: true
