# This is an appspec.yml template file for use with AWS CodeDeploy.

version: 0.0

os: linux

files:
  - source: /
    destination: /home/serviceapi/app

hooks:
  BeforeInstall:
    - location: scripts/prep-deploy.sh
      timeout: 60
      runas: root

  AfterInstall:
    - location: scripts/build-environment.sh
      timeout: 900
      runas: root

  ApplicationStart:
    - location: scripts/post-deploy.sh
      timeout: 120
      runas: root
