DOMAIN_NAME: serviceapi.security.mozilla.org
ZONE_ID:  ZBALOKPGJTQW
CERTIFICATE_ARN: arn:aws:acm:us-west-2:371522382791:certificate/77e8a1bd-8f66-455d-99a3-261c64c661ec
AUTH0_URL: auth.mozilla.auth0.com
AUDIENCE: https://serviceapi.security.mozilla.org/
ENVIRONMENT: prod
REGION: us-west-2
KMSGUID: 7e581152-11be-44eb-9867-ea25afff8981
RISKS_BUCKET_NAME: infosec-risk-data
RISKS_KEY_NAME: risks.json