DOMAIN_NAME: serviceapi.security.mozilla.org
ZONE_ID:  ZBALOKPGJTQW
CERTIFICATE_NAME: serviceapi.security.mozilla.org
AUTH0_URL: auth.mozilla.auth0.com
AUDIENCE: https://serviceapi.security.mozilla.org/
ENVIRONMENT: prod
REGION: us-west-2
KMSGUID: 7e581152-11be-44eb-9867-ea25afff8981