DOMAIN_NAME: serviceapi.security.allizom.org
ZONE_ID: Z13VQZ50081YZU
CERTIFICATE_ARN: arn:aws:acm:us-west-2:656532927350:certificate/436a9e26-6fc9-496d-a383-53b7c144e21a
AUTH0_URL: auth-dev.mozilla.auth0.com
AUDIENCE: https://serviceapi.security.allizom.org/
ENVIRONMENT: dev
REGION: us-west-2
KMSGUID: 6762fa27-618c-4c0b-83d4-ca42ffac454f
RISKS_BUCKET_NAME: infosec-risk-data-dev
RISKS_KEY_NAME: risks.json