service: servicemapper
custom:
  s3_bucket: mozilla-service-map-${opt:stage, self:provider.stage}
  s3_bucket_arn: arn:aws:s3:::${self:custom.s3_bucket}
  pythonRequirements:
    usePipenv: true
  wsgi:
    app: api.app
    packRequirements: false

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-west-2
  environment:
    INDICATOR_TABLE: ${opt:stage, self:provider.stage}-Indicators
    ASSET_TABLE: ${opt:stage, self:provider.stage}-Assets
    ASSET_GROUPS_TABLE: ${opt:stage, self:provider.stage}-AssetGroups
    ENVIRONMENT: dev
    REGION: ${opt:region, self:provider.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:BatchGetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
        - dynamodb:CreateTable
        - dynamodb:UpdateTable
        - dynamodb:GetRecords
        - dynamodb:BatchWriteItem
        - dynamodb:DescribeLimits
        - dynamodb:UpdateTimeToLive
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.INDICATOR_TABLE}"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:BatchGetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
        - dynamodb:CreateTable
        - dynamodb:UpdateTable
        - dynamodb:GetRecords
        - dynamodb:BatchWriteItem
        - dynamodb:DescribeLimits
        - dynamodb:UpdateTimeToLive
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.ASSET_TABLE}"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:BatchGetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
        - dynamodb:CreateTable
        - dynamodb:UpdateTable
        - dynamodb:GetRecords
        - dynamodb:BatchWriteItem
        - dynamodb:DescribeLimits
        - dynamodb:UpdateTimeToLive
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.ASSET_GROUPS_TABLE}"
    - Effect: Allow
      Action:
        - dynamodb:ListTables
        - dynamodb:DescribeLimits
        - dynamodb:DescribeReservedCapacity
        - dynamodb:DescribeReservedCapacityOfferings
      Resource: "*"
    - Effect: Allow
      Action:
        - s3:*
      Resource: ${self:custom.s3_bucket_arn}/*


functions:
  api:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}

  bucket:
    handler: bucket.event
    events:
      - s3:
          bucket: ${self:custom.s3_bucket}
          event: s3:ObjectCreated:*

plugins:
  - serverless-python-requirements
  - serverless-wsgi
