AWSTemplateFormatVersion: "2010-09-09"
Description: "Mozilla service-map roles"
Resources:
  ServiceMapRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      RoleName: ServiceMapRole
  ServiceMapInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    DependsOn: ServiceMapRole
    Properties:
      InstanceProfileName: "service-map-instance-profile"
      Roles:
        - Ref: ServiceMapRole
  ServiceMapCredstashRead:
    Type: "AWS::IAM::Policy"
    DependsOn: ServiceMapRole
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "dynamodb:GetItem"
              - "dynamodb:Query"
              - "dynamodb:Scan"
            Resource: "arn:aws:dynamodb:*:*:table/credential-store"
      PolicyName: servicemap-credstash
      Roles:
        - Ref: ServiceMapRole
  ServiceMapTagAccess:
    Type: "AWS::IAM::Policy"
    DependsOn: ServiceMapRole
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "ec2:DescribeTags"
            Resource: "*"
      PolicyName: service-map-describe-tags
      Roles:
        - Ref: ServiceMapRole
  ServiceMapS3:
    Type: "AWS::IAM::Policy"
    DependsOn: ServiceMapRole
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "s3:GetObject"
            Resource: "arn:aws:s3:::moz-service-map-dev/*"
      PolicyName: service-map-s3
      Roles:
        - !Ref ServiceMapRole
  ServiceMapCodeDeploy:
    Type: "AWS::IAM::Policy"
    DependsOn: ServiceMapRole
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "codedeploy:*"
            Resource: "arn:aws:codedeploy:*:*:application:service-map-*"
      PolicyName: service-map-code-deploy
      Roles:
        - Ref: ServiceMapRole
