---

- name: Create serviceapi user
  user:
    name: serviceapi

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - golang
    - net-tools
    - git
    - sudo

- name: Install dumb-init
  apt:
    deb: "{{ dumb_init_url }}"

- name: Set GOPATH
  lineinfile:
    dest: ~serviceapi/.profile
    line: "export GOPATH=$HOME/go"
    create: yes
    regexp: "^export GOPATH"

- name: Create go source path
  file:
    state: directory
    path: "~serviceapi/go/src/{{ source_postfix }}"
  become: yes
  become_user: serviceapi

- name: Clone service-map
  git:
    repo: "{{ servicemap_repo }}"
    version: "{{ servicemap_version }}"
    dest: "~serviceapi/go/src/{{ source_postfix }}"
  become: yes
  become_user: serviceapi

- name: Install service-map components
  shell: "source ~serviceapi/.profile && go install {{ source_postfix }}/{{ item }}"
  with_items:
    - servicelib
    - serviceapi
  args:
    executable: /bin/bash
  become: yes
  become_user: serviceapi

- name: Install serviceapi configuration file
  template:
    src: serviceapi.conf
    dest: /etc/serviceapi.conf
    mode: 0600
    owner: serviceapi
    group: serviceapi
